/* Pan-Asia Supermarket — shared store location data
   Used by the homepage map, the Locations index map, and individual store pages. */

const PAN_ASIA_LOCATIONS = [
  {
    id: "omaha",
    name: "Asian Market",
    city: "Omaha, NE",
    since: 2010,
    status: "open",
    address: "321 N. 76th St.",
    cityStateZip: "Omaha, NE 68114",
    phone: "(402) 391-2606",
    phoneHref: "tel:+14023912606",
    email: "asianmarketomaha@gmail.com",
    hours: [["Sun – Thu", "9:00 AM – 8:00 PM"], ["Fri – Sat", "9:00 AM – 8:30 PM"]],
    hoursNote: "Open every day of the year — may close earlier on major holidays.",
    departments: ["Produce", "Meat", "Live & Fresh Seafood", "Grocery", "Dairy", "Frozen", "Wine & Liquor", "Fresh Deli & Bakery", "Hot Food — Asia Bistro", "Boba Tea — Bubble Boba"],
    dining: [
      { name: "Asia Bistro", kind: "hotfood", hours: null, phone: null, phoneHref: null, orderUrl: null },
      { name: "Bubble Boba", kind: "boba", hours: null, phone: null, phoneHref: null, orderUrl: null }
    ],
    lat: 41.262072,
    lng: -96.030482,
    mapUrl: "https://g.page/asian-market-omaha?share",
    image: "assets/images/store-omaha.jpg",
    applyUrl: "https://docs.google.com/forms/d/1QfgeqlTwi9KZdfq7MPmSGV2q_AFLUQQDCKXUl0NytFM/viewform",
    social: { facebook: "https://www.facebook.com/Omaha76thDodge/", wechat: "https://u.wechat.com/kBYwwEesfZRrcp-Kw6qmSTU" },
    page: "locations/omaha.html"
  },
  {
    id: "overland-park-12035",
    name: "Pan-Asia Supermarket",
    city: "Overland Park, KS",
    subtitle: "12035 Metcalf Ave.",
    since: 2016,
    status: "open",
    address: "12035 Metcalf Ave.",
    cityStateZip: "Overland Park, KS 66213",
    phone: "(913) 345-9001",
    phoneHref: "tel:+19133459001",
    email: "PanAsiaKansas@gmail.com",
    hours: [["Mon – Sun", "9:00 AM – 8:30 PM"]],
    hoursNote: "Open 365 days a year.",
    departments: ["Produce", "Meat", "Live & Fresh Seafood", "Grocery", "Dairy", "Frozen", "Lottery", "Sushi", "Bakery", "Café — order online", "Boba Tea — order online"],
    dining: [
      { name: "Café", kind: "cafe", hours: [["Daily", "10:30 AM – 8:00 PM"]], phone: null, phoneHref: null, orderUrl: "https://www.onlineorder.abcpos.com/Kansas-cafe-boba/da83a69380f14c5fbe055b7f86b281b9" },
      { name: "Boba Tea", kind: "boba", hours: [["Daily", "10:30 AM – 8:00 PM"]], phone: null, phoneHref: null, orderUrl: "https://www.onlineorder.abcpos.com/Kansas-cafe-boba/da83a69380f14c5fbe055b7f86b281b9" }
    ],
    lat: 38.911268,
    lng: -94.667652,
    mapUrl: "https://goo.gl/maps/6QWWiyZDvNXeY3qr9",
    image: "assets/images/store-overland-park-12035.jpg",
    applyUrl: "https://docs.google.com/forms/d/1OJLPezBhRrxGj7rfa7PMu_tRhgiJ7G7_CvMh8ncsm3k/viewform",
    social: { facebook: "http://www.facebook.com/panasiakansas", wechat: "http://weixin.qq.com/r/p3tZQWTEZTkarSAi9y61" },
    page: "locations/overland-park-12035.html"
  },
  {
    id: "overland-park-10336",
    name: "Oriental Supermarket",
    city: "Overland Park, KS",
    subtitle: "10336 Metcalf Ave.",
    since: 2024,
    status: "open",
    address: "10336 Metcalf Ave.",
    cityStateZip: "Overland Park, KS 66212",
    phone: "(913) 341-3345",
    phoneHref: "tel:+19133413345",
    email: "OrientalKansas@gmail.com",
    hours: [["Mon – Sat", "9:00 AM – 8:30 PM"], ["Sunday", "9:00 AM – 7:00 PM"]],
    hoursNote: "Open 365 days a year.",
    departments: ["Produce", "Meat", "Seafood", "Grocery", "Dairy", "Frozen"],
    lat: 38.94026,
    lng: -94.669874,
    mapUrl: "https://goo.gl/maps/kFtV7RgmUy63tsGEA",
    image: "assets/images/store-overland-park-10336.jpg",
    applyUrl: "https://docs.google.com/forms/d/1C7PHJhChPiFpeoPLNsBGrhaLHBL7NEM4h2Tmqt-QXhc/viewform",
    page: "locations/overland-park-10336.html"
  },
  {
    id: "manchester",
    name: "Pan-Asia Supermarket",
    city: "Manchester, MO",
    subtitle: "Corporate Headquarters · Serving Greater St. Louis",
    since: 2017,
    status: "open",
    headquarters: true,
    address: "14246 Manchester Rd.",
    cityStateZip: "Manchester, MO 63011",
    phone: "(636) 220-9999",
    phoneHref: "tel:+16362209999",
    email: "PAMarket2@gmail.com",
    hours: [["Sun – Thu", "9:00 AM – 8:00 PM"], ["Fri – Sat", "9:00 AM – 8:30 PM"]],
    hoursNote: "Open every day of the year — may close earlier on major holidays.",
    departments: ["Produce", "Meat", "Live & Fresh Seafood", "Grocery", "Dairy", "Frozen", "Wine & Liquor", "Fresh Deli & Bakery"],
    dining: [
      { name: "China Bistro", kind: "hotfood", hours: [["Daily", "10:30 AM – 3:00 PM"], ["Daily", "3:30 PM – 6:45 PM"]], phone: "(636) 220-3144", phoneHref: "tel:+16362203144", orderUrl: "https://www.onlineorder.abcpos.com/ChinaBistro/ebd9b5529db940a9bceeb2a394c8b56e" },
      { name: "Bubble Cup TeaZone", kind: "boba", hours: null, phone: null, phoneHref: null, orderUrl: null }
    ],
    retailServices: [
      { name: "Korean Beauty Supply — The Face Shop", detail: "" },
      { name: "Zabiha Halal Meat Butcher Shop", detail: "Call (636) 675-4965" }
    ],
    corporatePositions: ["Corporate Accountant", "IT Manager", "Marketing Specialist / Manager", "HR Manager", "Software Developer", "Business / Data Analyst"],
    lat: 38.590733,
    lng: -90.505271,
    mapUrl: "https://goo.gl/maps/Hx3adpUrDxBrHMTT8",
    image: "assets/images/store-manchester.jpg",
    applyUrl: "https://docs.google.com/forms/d/1SVz23_ChLBZvmvADWcMtngB35kdssdt3lF8etDyekRY/viewform",
    social: { facebook: "https://www.facebook.com/PanAsiaSTLOUIS/", instagram: "https://www.instagram.com/panasiastlouis/", wechat: "http://weixin.qq.com/r/mWW2rqrERfc6re7N9zCL" },
    page: "locations/manchester.html"
  },
  {
    id: "tulsa",
    name: "Pan-Asia Supermarket of Tulsa",
    city: "Tulsa, OK",
    since: 2022,
    status: "open",
    address: "10003 E 71st St.",
    cityStateZip: "Tulsa, OK 74133",
    phone: "(918) 940-7570",
    phoneHref: "tel:+19189407570",
    email: "PanAsiaTulsa@gmail.com",
    hours: [["Sun – Thu", "9:00 AM – 8:00 PM"], ["Fri – Sat", "9:00 AM – 8:30 PM"]],
    hoursNote: "Open 365 days a year.",
    departments: ["Produce", "Meat", "Live & Fresh Seafood", "Grocery", "Dairy", "Frozen", "Lottery", "Wine & Liquor", "Fresh Deli & Bakery"],
    dining: [
      { name: "Jade Grill", kind: "hotfood", hours: [["Sun – Thu", "10:30 AM – 7:30 PM"], ["Fri – Sat", "10:30 AM – 8:00 PM"]], phone: "(918) 940-7572", phoneHref: "tel:+19189407572", orderUrl: null },
      { name: "Tsaocaa Boba Tea", kind: "boba", hours: [["Sun – Thu", "10:30 AM – 7:30 PM"], ["Fri – Sat", "10:30 AM – 8:00 PM"]], phone: "(918) 940-7573", phoneHref: "tel:+19189407573", orderUrl: null }
    ],
    lat: 36.060866,
    lng: -95.869745,
    mapUrl: "https://goo.gl/maps/Zr6n6aAg381TAUgJ8",
    image: "assets/images/store-tulsa.jpg",
    applyUrl: "https://docs.google.com/forms/d/14-LCqRnPbJa_NFo-Ef6wzgf3vwhbgwYkYeaJ0tYcywA/viewform",
    social: { facebook: "http://www.facebook.com/panasiatulsa", instagram: "https://www.instagram.com/panasiatulsa/", tiktok: "https://www.tiktok.com/@panasiatulsa", wechat: "https://u.wechat.com/kNLU_nRj1JP_6_-K7OSvORE" },
    page: "locations/tulsa.html"
  },
  {
    id: "milwaukee",
    name: "Pan-Asia Supermarket",
    city: "Milwaukee, WI",
    subtitle: "West Allis",
    since: 2025,
    status: "open",
    address: "6910 W Greenfield Ave.",
    cityStateZip: "West Allis, WI 53214",
    phone: "(414) 296-4678",
    phoneHref: "tel:+14142964678",
    email: "Milwaukee@PanAsiaMarket.com",
    hours: [["Sun – Thu", "9:00 AM – 8:00 PM"], ["Fri – Sat", "9:00 AM – 8:30 PM"]],
    hoursNote: "Open 365 days a year.",
    departments: ["Produce", "Meat", "Live & Fresh Seafood", "Grocery", "Dairy", "Frozen", "Bakery", "Sushi", "Café — order online", "Boba Tea — order online"],
    dining: [
      { name: "Café", kind: "cafe", hours: [["Daily", "10:30 AM – 7:30 PM"]], phone: null, phoneHref: null, orderUrl: "https://www.onlineorder.abcpos.com/Milwaukee-cafe/a2366adad7a54a71a183e09cc035c342" },
      { name: "Boba Tea", kind: "boba", hours: [["Daily", "10:30 AM – 7:30 PM"]], phone: null, phoneHref: null, orderUrl: "https://www.onlineorder.abcpos.com/Milwaukee-boba/8aa15257873f43c4919df450f4d1d265" }
    ],
    lat: 43.017074,
    lng: -87.998986,
    mapUrl: "https://maps.app.goo.gl/9HKeYoSRKjhtwS1v6",
    image: "assets/images/store-milwaukee.jpg",
    applyUrl: "https://forms.gle/fvQFVUo1YGgvGS5b7",
    social: { facebook: "http://www.facebook.com/panasiakansas", wechat: "https://u.wechat.com/kMSCCqSnfk-REep3HP7kTys" },
    page: "locations/milwaukee.html"
  },
  {
    id: "nashville",
    name: "Pan-Asia Supermarket",
    city: "Nashville, TN",
    subtitle: "Antioch",
    since: 2026,
    status: "open",
    address: "5255 Hickory Hollow Pkwy",
    cityStateZip: "Antioch, TN 37013",
    phone: "(615) 535-5255",
    phoneHref: "tel:+16155355255",
    email: "Nashville@PanAsiaMarket.com",
    hours: [["Sun – Thu", "9:00 AM – 8:00 PM"], ["Fri – Sat", "9:00 AM – 8:30 PM"]],
    hoursNote: "Open 365 days a year.",
    departments: ["Produce", "Meat", "Live & Fresh Seafood", "Grocery", "Dairy", "Frozen", "Bakery", "Sushi"],
    dining: [
      { name: "Café", kind: "cafe", hours: [["Daily", "10:30 AM – 7:30 PM"]], phone: null, phoneHref: null, orderUrl: "https://www.onlineorder.abcpos.com/Pan-Asia-Supermarket-of-Nashville/ae224714258d47c18964d65717c4f8b3" },
      { name: "Boba Tea", kind: "boba", hours: [["Daily", "10:30 AM – 7:30 PM"]], phone: null, phoneHref: null, orderUrl: "https://www.onlineorder.abcpos.com/Pan-Asia-Supermarket-of-Nashville/9163da2564704defa9176e290c301cc3" }
    ],
    lat: 36.052002,
    lng: -86.667104,
    mapUrl: "https://maps.app.goo.gl/ssfH8AYfTABHZRLh8",
    image: "assets/images/store-nashville.jpg",
    applyUrl: "https://docs.google.com/forms/d/1a4n_P7llgudLylK4r_NBiNn4OWycwVtKaO_oWoxwEvM/viewform",
    social: { facebook: "http://www.facebook.com/panasiakansas", wechat: "https://u.wechat.com/kIky7t_SzaDW8Sq1CgCl0Pw" },
    page: "locations/nashville.html"
  },
  {
    id: "san-antonio",
    name: "Pan-Asia Supermarket",
    city: "San Antonio, TX",
    status: "coming-soon",
    comingLabel: "Opening Early 2027",
    address: "3713 Colony Dr",
    cityStateZip: "San Antonio, TX 78230",
    lat: 29.532327,
    lng: -98.557535,
    mapUrl: "https://maps.app.goo.gl/c4rQ8hayC1dhTAkG9",
    image: "assets/images/store-san-antonio.jpg",
    page: "locations/san-antonio.html"
  },
  {
    id: "detroit",
    name: "Pan-Asia Supermarket",
    city: "Detroit, MI",
    status: "coming-soon",
    comingLabel: "Opening 2027",
    address: null,
    cityStateZip: "Detroit, MI",
    lat: 42.331551,
    lng: -83.04664,
    mapUrl: null,
    image: null,
    page: "locations/detroit.html"
  }
];

if (typeof module !== "undefined") {
  module.exports = PAN_ASIA_LOCATIONS;
}
